/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gelaigelai.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2018
 * 
 * XDoclet definition:
 * @struts.form name="commentForm"
 */
public class CommentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** commentInfo property */
	private String commentInfo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the commentInfo.
	 * @return String
	 */
	public String getCommentInfo() {
		return commentInfo;
	}

	/** 
	 * Set the commentInfo.
	 * @param commentInfo The commentInfo to set
	 */
	public void setCommentInfo(String commentInfo) {
		this.commentInfo = commentInfo;
	}
}