/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gelaigelai.struts.action;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.transaction.Transaction;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gelaigelai.common.Transform;
import com.gelaigelai.domain.Article;
import com.gelaigelai.domain.Articleimg;
import com.gelaigelai.domain.Image;
import com.gelaigelai.service.ArticleService;
import com.gelaigelai.struts.form.CommentForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2018
 * 
 * XDoclet definition:
 * @struts.action path="/artilce" name="commentForm" scope="request" validate="true"
 */
public class ArtilceAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CommentForm commentForm = (CommentForm) form;// TODO Auto-generated method stub
		Integer articleId=Integer.parseInt(request.getParameter("articleId"));
	ArticleService articleService=new ArticleService();
	Article article= articleService.getArticleDAO().findById(articleId);
	List<Articleimg>images=articleService.getArticleImage(articleId);
	String title=article.getTitle();
	String info =article.getAinfo();
	String author=article.getAauthor();
	Date date=article.getAdate();
	String dateString=Transform.DateToString(date);
	System.out.println(info);
	request.setAttribute("date", dateString);
	request.setAttribute("author", author);
	request.setAttribute("info", info);
	request.setAttribute("title", title);
	request.setAttribute("images", images);
	return mapping.findForward("ok");
	
	}
}