/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gelaigelai.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.mapping.Array;

import com.gelaigelai.domain.Article;
import com.gelaigelai.service.ArticleService;
import com.gelaigelai.service.PoemService;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ArticlemainAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		Integer userId=Integer.parseInt(request.getParameter("userId").toString());
		request.setAttribute("userId", userId);
	ArticleService articleService=new ArticleService();
	List<Article>articles=articleService.getArticle();
	request.setAttribute("article", articles);
	return mapping.findForward("ok");
	
	}
}