/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gelaigelai.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import org.springframework.context.ApplicationContext;

import com.gelaigelai.domain.User;
import com.gelaigelai.service.UserService;
import com.gelaigelai.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-30-2018
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 * @struts.action-forward name="ok" path="/index.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	int flag=0;
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		String username=loginForm.getUsername();
		String password=loginForm.getPassword();

		UserService userService=new UserService();
		User u=new User();
		u.setUsername(username);
		u.setPassword(password);
		if(userService.checklogin(u)){
			
			flag=1;
			List<User> myUser=userService.getUserDAO().findByUsername(username);
			request.setAttribute("userId",myUser.get(0).getIdUser());
		    request.setAttribute("loginFlag", flag);
		    System.out.println("ok");
		 
			return mapping.findForward("ok");
		}
		else{
			request.setAttribute("loginError", "哎呦，对不起哦，你输入的信息有误！请重新输入");
			request.getSession().setAttribute("loginFlag", flag);
			 System.out.println("fail");
			return mapping.findForward("fail");
		}
	}
}