/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gelaigelai.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gelaigelai.common.Transform;
import com.gelaigelai.domain.Poem;
import com.gelaigelai.service.PoemService;
import com.gelaigelai.service.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 06-03-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ok" path="/myaccount.jsp"
 */
public class PersonalAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		Integer userId;
		userId=Integer.parseInt(request.getParameter("userId"));
		//获取具体的页数
		int page=Integer.parseInt(request.getParameter("page"));
		
		UserService userService=new UserService();
		PoemService poemService =new PoemService();
		ArrayList<Poem>poemsList=new ArrayList<Poem>();
		poemsList=poemService.getPoemByUserId(userId);
		ArrayList<Poem>choosepoems=getPoemList(poemsList, page);
		
		request.setAttribute("poemlist", choosepoems);
		request.setAttribute("userId", userId);
		for(Poem p:choosepoems){
			System.out.println(p.getPinfo());
		}
		
		return mapping.findForward("ok");
	}
	public ArrayList<Poem> getPoemList(ArrayList<Poem> poemlist,int page){
		int length=poemlist.size();
		int k=(page-1)*3;
		ArrayList<Poem>choosePoems=new ArrayList<Poem>();
		choosePoems.add(poemlist.get(k));
		choosePoems.add(poemlist.get(k+1));
		choosePoems.add(poemlist.get(k+2));
		return choosePoems;
	}

}