/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gelaigelai.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gelaigelai.domain.Poem;
import com.gelaigelai.domain.Poet;
import com.gelaigelai.domain.Song;
import com.gelaigelai.domain.SongDAO;
import com.gelaigelai.service.PoemService;
import com.gelaigelai.service.PoetService;
import com.gelaigelai.service.SongService;

/** 
 * MyEclipse Struts
 * Creation date: 03-28-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ShowPoemAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		Integer poemId=Integer.parseInt(request.getParameter("poemid"));
		PoemService poemService=new PoemService();
		SongService songService=new SongService();
		PoetService poetService=new PoetService();
		Poem poem=poemService.getPoemDAO().findById(poemId);
		System.out.println(poem.getType().getIdtype());
		List <Song>songList=songService.getSongByType(poem.getType().getIdtype());
		
	    Poet poet=poetService.getPoetDAO().findById(poem.getPoet().getIdpoet());
	    //展示的诗歌
		request.setAttribute("poem",poem);
		//诗歌配套的歌曲
		request.setAttribute("songs",songList);
		//写诗的作者
		request.setAttribute("poet", poet);
		Integer userId=Integer.parseInt(request.getParameter("userId").toString());
		request.setAttribute("userId", userId);
		return mapping.findForward("ok");
		
	}
}